#!/usr/bin/python
import time
import smtplib

errors = []
timestampfile = '/media/backup/timestamp.txt'
nowtime = int(time.time())

try:
    timestampread = open(timestampfile, 'r').read()
except IOError, e:
    errors.append("Timestamp file not found")
else:
    try:
        backuptime = int(timestampread)
    except IOError, e:
        errors.append("Timestamp file corrupt")
    else:
        if nowtime - backuptime > 86400:
            errors.append("V1SB backup is more than one day old")

if len(errors):
        msg = "From: backup@pelagodesign.com\r\n"
        msg = msg + "To: backup@pelagodesign.com\r\n"
        msg = msg + "Subject: V1SB Backup Error\r\n"
        msg = msg + "\r\n"
        msg = msg + "ERROR: The following backup problems were found:\n"
        msg = msg + "\n".join(errors)+"\n"
        server = smtplib.SMTP('192.168.1.42')
        server.sendmail("backup@pelagodesign.com", "backup@pelagodesign.com", msg)
        server.quit()
