#!/usr/bin/python

import sys
import subprocess

p1 = subprocess.Popen(['ps','aux'], stdout=subprocess.PIPE)
p2 = subprocess.Popen(['grep','-c','httpd'], stdin=p1.stdout, stdout=subprocess.PIPE)
p1.stdout.close()
numprocs = p2.communicate()[0].splitlines()[0]
if(int(numprocs) > 70):
    sys.exit(75)
else:
    sys.exit(0)
