#!/usr/bin/python
import datetime, sys, requests

#token = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
atheleteid = xxxxxxxxx

if len(sys.argv) > 1:
    today = sys.argv[1]
else:
    today = str(datetime.date.today())

gpx = 'commute.gpx'
gpxout = ''

for line in open(gpx):
    gpxout += line.replace('YYYY-MM-DD', today)

headers = {'Authorization': 'Bearer ' + token}
payload = {'name': 'Commute', 'activity_type': 'ride', 'data_type': 'gpx', 'commute': '1'}
files = {'file': gpxout}
r = requests.post('https://www.strava.com/api/v3/uploads', headers=headers, data=payload, files=files)
print vars(r)
